### ISSUE TITLE
Ethetic Green Blocks

### ISSUE THREAD

**Issue by Grand-Trizmo** [AllTheMods/ATM3-Lite#19] opened 2018-08-13 20:52 UTC
recipe doesnt work for the blocks im thinking the ore data for the different quartz blocks is breaking it
![Image of Recipe](https://i.triz.moe/1534193429.png)
Gif of the recipe it outputs regular Ethetic Blocks
https://i.triz.moe/1534193535.gif

**Comment by Sleeeper** [comment] 2018-08-13 20:55
never had a problem with it, uses chiseled quartz blocks at the left

**Comment by Grand-Trizmo** [comment] 2018-08-13 20:59
thats what i was using in the gif i put

**Comment by sebi2306** [comment] 2018-08-13 22:26
duplicate of #13

**Closed** 2018-08-27 01:51 UTC
